name: Build and Deploy Frontend

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches:
      - 'dev'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present

    - name: Deploy to Server
      uses: kostya-ten/ssh-server-deploy@v4
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: 22
        username: ${{ secrets.SERVER_SK_R }}
        password: ${{ secrets.SERVER_SK_R_PASSWD }}
        scp_source: dist/
        scp_target: ${{ secrets.SERVER_WORKDIR }}
        before_script: |
          df -h
        after_script: |
          echo ====================done===================
